version: '2.2'

services:
    yaac:
        image: yaac #ghcr.io/8ch9azbsfifz/docker-wsjtx
        privileged: true
        environment:
            - MYCALL=FIXME
            - MYGRID=FIXME
        #volumes:
        #    - /dev/bus/usb:/dev/bus/usb
            #- ./WSJT-X.ini:/root/.config/WSJT-X.ini
        ports:
            - 8081:8080
        #    - 2237:2237/udp
